import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] })


export const metadata: Metadata = {
  title: 'Track Tales | Songdew',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/S_logo_RGB.png" /> */}
        <link rel="shortcut icon" href="/S_logo_RGB.png" type="image/x-icon" />
        {/* <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} /> */}
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
